"""add image_fileid column to posts table

Revision ID: 21adc1bce9ee
Revises: 076fe872bf25
Create Date: 2026-05-11 09:30:10.425950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21adc1bce9ee'
down_revision: Union[str, Sequence[str], None] = '076fe872bf25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_fileid', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_fileid')
    # ### end Alembic commands ###
